language: python
python:
- '2.7'
- '2.6'
install:
- pip install -r ./ci/requirements.txt
- python setup.py develop
script:
- flake8 .
- nosetests -v
notifications:
  hipchat:
    rooms:
      secure: frn3Xhgyrn8vutgNJeiTLauMalF9lqVhXxAT/0ff5OKYfzEWM6PgnDSB8VFnNxi09IfSQaXGgZJrCQgdEsbrMWAxaW9Ycxv2rZ9Av/dM7THz/HjsoipBXnXkcErBTOH9bBJU/ICDHzP2oqmfEojBH/zFIeMqpaySUPVgC4HDWEs=
      template:
        - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'

